import React from 'react';
import MotionEffects from './MotionEffects';
import {Factory, Truck, Wrench, HardHat, UsersThree, ShieldCheck, Handshake, ChartLineUp, Recycle, Gear, Quotes, ArrowUpRight} from '@phosphor-icons/react';
import {p,tables,title,range,services,contacts,achievements,headOffice} from './content';
import {Header,Footer,Button,Photo,SectionHeading,Checks,PageHero,ContactBanner,ContactCard,DataTable,OfficeMap} from './components';

const icons=[Truck,Factory,HardHat,Gear,Wrench,ShieldCheck,Recycle,Factory,Gear,UsersThree];
function Metrics(){return <div className="container metrics">{[['₹80 Cr.','Annual Turnover'],['3,200+','Workforce Strength'],['4','Verticals'],['18','Branch Offices']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div>}
function ServiceCard({index}){const Icon=icons[index];const text=services[index];const parts=text.split(':');return <a className={`service-card service-${index}`} href={`/services/#service-${index}`}><Icon size={42} weight="light" aria-hidden="true"/><h3>{parts[0]}</h3>{parts[1]&&<p>{parts[1].trim()}</p>}<ArrowUpRight className="card-arrow" size={20} aria-hidden="true"/></a>}
function Testimonials(){return <section className="section container"><SectionHeading heading={title(p[405])} href="/contact/" label={title(p[430])}/><div className="testimonials">{[406,408,410].map((i,j)=><figure className={`quote quote-${j}`} key={i}><Quotes size={34} weight="light" aria-hidden="true"/><blockquote>{p[i]}</blockquote><figcaption>{p[i+1]}</figcaption></figure>)}<Photo name="team"/></div></section>}
function ResultCards(){return <div className="result-grid">{[0,4,7].map((n,i)=><a className={`result-card result-${i}`} href={`/presence/#achievement-${n}`} key={n}><Photo name={['team','workshop','plant'][i]}/><div><p className="eyebrow">{achievements[n][0]}</p><h3>{achievements[n][3]}</h3><p>{achievements[n][1]}</p><ArrowUpRight size={23} aria-hidden="true"/></div></a>)}</div>}
function Home(){return <><section className="hero"><Photo name="hero" eager/><div className="hero-content container"><span className="hero-pill">{p[195]}</span><h1>Your Trusted Partner in<br/> <span>Industrial</span> Operations</h1><p>{p[12]}</p><div className="button-row"><Button href="/services/">{title(p[142])}</Button><Button href="/company/" outline>{title(p[5])}</Button></div></div></section><Metrics/>
 <section className="section container about"><SectionHeading eyebrow={title(p[5])} heading={p[35]} href="/company/" label="Company Profile"/><div className="about-grid"><Photo name="plant" className="about-tall"/><Photo name="hero" className="about-small"/><div className="about-copy"><h3>{p[423]}</h3><p>{p[8]}</p><Checks items={[p[424],p[426]]}/></div><p className="about-statement">{p[7]}</p></div><div className="company-strip"><h3>{title(p[82])}</h3><div>{range(83,87).map(s=><a href="/company/#group" key={s}>{s.split(' Proprietor:')[0].split(':')[0]}</a>)}</div></div></section>
 <section className="section services-section"><div className="container services-feature"><div className="service-grid">{[0,4,2,1].map(i=><ServiceCard index={i} key={i}/>)}</div><div className="service-poster"><Photo name="plant"/><div><p className="eyebrow">{title(p[142])}</p><h2>{p[152]}</h2><p>{p[14]}</p><Button href="/services/">{title(p[142])}</Button></div></div></div></section>
 <section className="section container strengths"><SectionHeading heading={title(p[389])} center/><div className="strengths-grid"><div>{range(390,392).map((s,i)=>{const Icon=[UsersThree,ChartLineUp,Gear][i];return <article key={s}><Icon size={34} weight="light"/><h3>{s}</h3></article>})}</div><Photo name="plant"/><div>{range(393,395).map((s,i)=>{const Icon=[Handshake,ShieldCheck,Factory][i];return <article key={s}><Icon size={34} weight="light"/><h3>{s}</h3></article>})}</div></div></section>
 <section className="section gallery-section"><div className="container"><SectionHeading eyebrow={title(p[194])} heading={p[195]} href="/presence/" label="National Presence"/><p className="gallery-intro">{p[196]}</p></div><div className="industrial-gallery">{['hero','workshop','team','plant'].map((n)=><Photo name={n} key={n}/>)}</div></section>
 <Testimonials/><ContactBanner/>
 <section className="section container"><SectionHeading eyebrow={title(p[34])} heading={p[35]} center/><div className="leadership-preview">{[tables[1][1],tables[1][2],tables[1][5]].map(r=><article key={r[1]}><div className="leadership-monogram" aria-hidden="true"><UsersThree size={58} weight="light"/></div><h3>{r[1]}</h3><p>{r[2]}</p><span>{r[3]}</span></article>)}</div><div className="center-action"><Button href="/company/#leadership">{title(p[34])}</Button></div></section>
 <section className="image-callout"><Photo name="team"/><div className="container"><h2>{title(p[422])}</h2><p>{p[425]}</p><Button href="/company/#partnership">{title(p[422])}</Button></div></section>
 <section className="section container"><SectionHeading eyebrow={title(p[258])} heading={p[302]} href="/presence/#achievements" label={title(p[382])}/><ResultCards/></section></>}

function Company(){return <><PageHero heading={title(p[5])} description={p[35]}/><section className="section container company-intro"><Photo name="plant"/><div><p className="eyebrow">SAHU &amp; COMPANIES</p><h2 className="profile-heading">Committed to Industry, People, and Progress.</h2><p className="profile-facts">{p[2]}</p>{range(6,8).map(s=><p key={s}>{s}</p>)}</div></section><section className="section pale"><div className="container"><SectionHeading heading={title(p[10])}/><div className="vision-grid"><article><h3>{p[11]}</h3><p>{p[12]}</p><p>{p[13].replace(' Mission:','')}</p></article><article><h3>Mission:</h3><Checks items={range(14,17)}/></article></div><h2 className="subheading">{title(p[20])}</h2><div className="values-grid">{tables[0][0].map((s,i)=><article key={s}><ShieldCheck size={28}/><h3>{s}</h3><p>{tables[0][1][i]}</p></article>)}</div></div></section>
 <section className="section container" id="leadership"><SectionHeading heading={title(p[34])}/><div className="leadership-list">{tables[1].slice(1).map(r=><article key={r[1]}><h3>{r[1]}</h3><p>{r[2]}</p><span>{r[3]}</span></article>)}</div></section>
 <section className="section pale" id="group"><div className="container"><SectionHeading heading={title(p[82])}/><div className="group-list">{range(83,87).map(s=><p key={s}>{s}</p>)}</div></div></section>
 <section className="section container"><SectionHeading heading={title(p[90])}/><div className="timeline">{tables[2].slice(1,-1).map((r,i)=><article key={i}><strong>{r[0]}</strong><p>{r[1]}</p></article>)}</div><p>{p[139]}</p></section>
 <section className="section pale"><div className="container two-column"><div><h2>{title(p[398])}</h2><Checks items={range(399,402)}/></div><div><h2>{title(p[414])}</h2><Checks items={range(415,419)}/></div></div></section><section className="section container" id="partnership"><SectionHeading heading={title(p[422])}/><Checks items={range(423,427)}/></section><ContactBanner/></>}
function Services(){return <><PageHero heading={title(p[142])} description={p[14]}/><section className="section container"><div className="full-services">{services.map((s,i)=>{const Icon=icons[i];return <article id={`service-${i}`} key={s}><Icon size={38} weight="light"/><div><h2>{s.split(':')[0]}</h2>{s.includes(':')&&<p>{s.split(':')[1]}</p>}</div></article>})}</div></section><section className="section pale"><div className="container"><DataTable data={tables[3]} caption={p[154]}/></div></section><section className="section container"><SectionHeading heading={title(p[389])}/><div className="values-grid">{range(390,395).map(s=><article key={s}><ChartLineUp size={30}/><h3>{s}</h3></article>)}</div></section><ContactBanner/></>}
function Presence(){return <><PageHero heading={title(p[194])} description={p[196]}/><section className="section container"><SectionHeading heading={p[195]}/><DataTable data={tables[4]} caption={p[197]}/></section><section className="section pale"><div className="container"><DataTable data={tables[5]} caption={p[266]}/></div></section><section className="section container"><SectionHeading heading={title(p[258])}/><Checks items={range(259,263)}/></section><section className="section pale" id="achievements"><div className="container"><SectionHeading heading={p[302]}/><div className="achievement-list">{achievements.map((r,i)=><details key={i} id={`achievement-${i}`} open={i===0}><summary><span><small>{r[0]} · {r[1]}</small><strong>{r[3]}</strong></span><span className="disclosure-symbol" aria-hidden="true"/></summary><div><p className="eyebrow">{r[2]}</p><p>{r[4]}</p></div></details>)}</div></div></section><section className="section container"><SectionHeading heading={title(p[382])}/><Checks items={range(383,386)}/></section><Testimonials/><ContactBanner/></>}
function Contact(){return <><PageHero heading={title(p[430])} description={p[431]}/><section className="section container"><div className="contact-grid">{contacts.map(c=><ContactCard contact={c} key={c.name}/>)}</div><div className="office"><div><p className="eyebrow">{title(p[442])}</p><h2>{p[443].split(' PAN:')[0]}</h2><p>{'PAN:'+p[443].split(' PAN:')[1]}</p><p>{p[444]}</p><a href={`mailto:${headOffice.email}`}>{headOffice.email}</a><br/><a href={`tel:${headOffice.phone.replace(/\s/g,'')}`}>{headOffice.phone}</a><p className="office-tagline">At SahuConnect, We Connect More Than Labor – We Connect Aspirations, Expertise, And Growth.</p><a href="https://www.sahuconnect.com">www.sahuconnect.com</a></div><OfficeMap/></div></section></>}
export const routes={'/':Home,'/company/':Company,'/services/':Services,'/presence/':Presence,'/contact/':Contact};
export default function App({path='/'}){const Page=routes[path]||Home;return <><a className="skip-link" href="#main">{path==='/'?'SAHUCONNECT':navLabel(path)}</a><div id="top"/><Header path={path}/><main id="main"><Page/></main><Footer/><MotionEffects/></>}
function navLabel(path){return ({'/company/':'Company Profile','/services/':'Services','/presence/':'National Presence','/contact/':'Connect With Us'})[path]||'SAHUCONNECT'}
