import React, {useEffect, useRef, useState} from 'react';
import {ArrowUpRight, List, X, EnvelopeSimple, Phone, ArrowRight, CheckCircle, Factory, MapPin} from '@phosphor-icons/react';
import {p, title, nav, contacts, assets, headOffice} from './content';

export function Button({href,children,outline=false}) {return <a className={`button ${outline?'outline':''}`} href={href}>{children}<ArrowUpRight size={16} aria-hidden="true"/></a>}
export function Photo({name,className='',eager=false}) {return <img className={`photo ${className}`} src={assets[name]} alt="" width={name==='hero'?1983:1200} height={name==='hero'?793:1400} loading={eager?'eager':'lazy'} decoding="async"/>}
export function Brand(){return <a className="brand" href="/" aria-label="SAHUCONNECT"><span>SAHU</span>CONNECT<span className="brand-mark" aria-hidden="true"/></a>}
export function Header({path}) {
 const [open,setOpen]=useState(false);const toggle=useRef(null);const panel=useRef(null);
 useEffect(()=>{if(!open)return;const onKey=e=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}if(e.key==='Tab'){const items=[toggle.current,...panel.current.querySelectorAll('a')];const index=items.indexOf(document.activeElement);if(e.shiftKey&&index===0){e.preventDefault();items.at(-1).focus()}else if(!e.shiftKey&&index===items.length-1){e.preventDefault();items[0].focus()}}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[open]);
 return <header className={path==='/'?'site-header on-hero':'site-header'}><div className="topbar"><div className="container"><span><Factory size={14}/>{p[195]}</span><a href={`tel:${headOffice.phone.replace(/\s/g,'')}`}><Phone size={13}/>{headOffice.phone}</a><a href={`mailto:${headOffice.email}`}><EnvelopeSimple size={14}/>{headOffice.email}</a></div></div><div className="container nav-wrap"><Brand/><button ref={toggle} className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-controls="navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><List className="menu-lines" size={26} aria-hidden="true"/><X className="menu-close" size={26} aria-hidden="true"/></button><nav ref={panel} id="navigation" className={open?'navigation open':'navigation'} aria-label="Main navigation">{nav.slice(0,-1).map(([href,label])=><a key={href} href={href} aria-current={path===href?'page':undefined}>{label}</a>)}<Button href="/contact/">{title(p[430])}</Button></nav></div></header>
}
export function SectionHeading({eyebrow,heading,href,label,center=false}) {return <div className={`section-heading ${center?'center':''}`}><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{heading}</h2></div>{href&&<Button href={href}>{label}</Button>}</div>}
export function Checks({items}){return <ul className="checks">{items.map(t=><li key={t}><CheckCircle weight="fill" size={16} aria-hidden="true"/><span>{t}</span></li>)}</ul>}
export function PageHero({heading,description}){return <section className="page-hero"><Photo name="hero" eager/><div className="container"><p className="eyebrow">SAHUCONNECT</p><h1>{heading}</h1>{description&&<p>{description}</p>}</div></section>}
export function ContactCard({contact}) {return <article className="contact-card"><h3>{contact.name}</h3><p>{contact.role}</p><a href={`mailto:${contact.email}`}><EnvelopeSimple size={18}/>{contact.email}</a>{contact.phones.map(t=><a key={t} href={`tel:${t.replace(/\s/g,'')}`}><Phone size={17}/>{t}</a>)}</article>}
export function ContactBanner(){return <section className="contact-banner"><Photo name="plant"/><div className="container contact-banner-inner"><div><p className="eyebrow">{title(p[430])}</p><h2>{p[431]}</h2><Button href="/contact/">{title(p[430])}</Button></div><ContactCard contact={contacts[0]}/></div></section>}
export function DataTable({data,caption}){return <div className="table-wrap" tabIndex={0} role="region" aria-label={caption}><table><caption>{caption}</caption><thead><tr>{data[0].map((c,i)=><th scope="col" key={i}>{c}</th>)}</tr></thead><tbody>{data.slice(1).map((r,i)=><tr key={i}>{r.map((c,j)=>j===0?<th scope="row" key={j}>{c}</th>:<td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export function Footer(){return <footer><div className="container footer-grid"><div><Brand/><p>Your Growth, Our Mission</p><p>{p[12]}</p></div><div><h3>{title(p[5])}</h3>{nav.slice(1).map(([href,label])=><a key={href} href={href}>{label}</a>)}</div><div><h3>{title(p[142])}</h3>{[144,145,147,150].map(i=><a key={i} href={`/services/#service-${i-143}`}>{p[i].split(':')[0]}</a>)}</div><div><h3>{title(p[442])}</h3><p><MapPin size={16}/>{p[443].split(' PAN:')[0]}</p><a href={`mailto:${headOffice.email}`}>{headOffice.email}</a><a href={`tel:${headOffice.phone.replace(/\s/g,'')}`}>{headOffice.phone}</a></div></div><div className="container footer-bottom"><span>SAHUCONNECT</span><a href="https://www.sahuconnect.com">www.sahuconnect.com</a><a href="#top" aria-label="Back to top"><ArrowRight className="up-arrow" size={20}/></a></div></footer>}

export function OfficeMap(){return <div className="office-map"><iframe title="SAHU HOUSE ? Head Office" src="https://www.google.com/maps?q=SAHU%20HOUSE%20B-128%20Sector%2020%20Belapur%20Navi%20Mumbai&ftid=%2Fg%2F11qgfbc1ms&z=17&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a className="office-map-link" href="https://share.google/kX75Gvdt1NaLTtjBO" target="_blank" rel="noopener noreferrer"><MapPin size={18} aria-hidden="true"/>{title(p[442])}<ArrowUpRight size={16} aria-hidden="true"/></a></div>}
